device_id = "45295259-d7af-46e6-92d2-4919b9cbfcd8"
access_token = "13480092-62d6-48d6-b051-c89f31084b5b"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:85fd:cce3:9f92:8c26:16de"
wg_private_key = "kCK/VmV/QFvJBhJ8FhnAR+EZT9mOwcVE0evzjrkOklI="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "/7nF"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "104.16.24.84"
